mapeamento_motivo_fluencia = {
    "Quero viajar e viver experiências marcantes me comunicando com confiança": [
        "viajar", "viagem", "turismo", "conhecer", "experiencia", "comunicar", "visitar", "lugares", "mochilao", "conversação", "fins turísticos", "viagem", "conhecer lugares", "mochilao", "curso no exterior", "turismo", "estudar fora", "visitá-la", "Desejo falar fluentemente para conversar com pessoas que tenham deficiência e que residam em países com idioma espanhol, e também como sou massoterapeuta posso vir a trabalhar em locais que recebam turistas que falem esse idioma.", "para viagens", "viagens e negócios", "melhor comunicação em viagens", "viagens futuras", "comunicação em viagens", "para dialogar com gringos", "viagens e conversas", "para realizar viagens", "para facilitar a comunicação", "para conversar com meu amigos argentinos", "tenho duas viagens", "viajo sempre para o Peru", "viajar fluentemente", "não passar perrengue nas viagens", "segurança em viagens", "para não passar perrengue nas viajens", "auxílio em viagens", "para usar e aproveitar mais nas viagens", "viagens", "independência nas viagens", "me tornar poliglota", "fui ao chile mês passado e passei dificuldades","viajar tranquilo", "abertura de horizonte", "pretendo morar lá", "dialogar", "conversar tranquilo", "para me relacionar com nativos", "me comunicar com nativos", "para conversar", "para conversar bem", "para conversar com segurança e rapidez", "ter melhor desenvoltura em viagens", "interação no meio social", "para sair do país", "poder sair do país", "para não depender de intérprete", "comunicar", "estrangeiro", "migrante", "imigrante", "pra conversar", "para dialogar", "para se comunicar com pessoas", "me comunicar melhor com latinos", "Pra trabalhar, e viajar,e também falar bem", "Pq, pra mim, é mais fácil que inglês e uma língua mto usada lá fora"
    ],
    "Conquistar um emprego melhor e ganhar mais": [
        "emprego", "trabalho", "vaga", "carreira", "salario", "ganhar", "profissao", "empresa", "melhoria curricular",  "trabalho", "vaga", "emprego", "profissional", "área profissional", "cargo técnico", "currículo", "carreira", "empresa", "ambiente de trabalho", "ganhar mais", "promoção", "exportação", "oportunidade de emprego", "empresa", "trabalho exige", "área profissional", "grupo argentino", "cargo técnico", "vaga", "emprego", "fornecedor espanhol", "prova de suficiência", "crescer profissionalmente", "para crescer profissionalmente", "abrir novos horizontes", "razões profissionais", "negócios", "expansão de negócios", "para trabalhar", "profissionalmente", "trabalhar meu cérebro", "ficar competitivo no mercado", "para prestar concurso público", "facilitar network", "para reuniões corporativas", "para colocar no currículo", "ter um futuro melhor", "vaga", "carreira", "reconhecimento profissional", "reconhecimento", "serviço", "influência profissional", "minha área de atuação será com américa latina", "modelo", "quero abrir um restaurante com cozinha móvel", "repertório", "interação internacional", "mercado", "plataforma de tradução", "para ensinar alunos", "dar aulas em colégio", "dar aulas", "reconhecimento acadêmico", "formação", "progresso", "amigos de trabalho", "profissão", "crescimento profissional", "influência profissional", "trabalho com comex", "curriculo", "qualificacao", "oportunidade", "abrir portas", "incrementar currículo", "Networking", "Soy palestrante y tengo invitación para hacer en español "
    ],
    "Morar no exterior": [
        "morar", "mudanca", "exterior", "residir", "me mudar", "quero me mudar", "uruguai", "fora do brasil", "Mudando de país", "morar fora", "morar na espanha", "morar na argentina", "vivo na espanha", "vivo na argentina", "estou morando", "minha filha mora", "mudança de país", "vou morar", "residir", "casar com estrangeiro", "quero sair desse país", "moro no py", "vou morar", "residir fora", "residência no exterior", "mudar de país", "viver em outro país", "viver fora", "vou residir lá", "viver na europa", "meu namorado em lima/peru", "sou casada com espanhol", "pretendo viver período na espanha", "fronteira", "vou para o peru", "peru", "argentina", "vivo na argentina", "assunção", "espanha", "morar fora", "estou morando na espanha", "sou estudante no paraguai"
    ],
    "Gosto do idioma e quero aprender por hobby": [
        "gosto", "amo", "adoro", "encanta", "interesse", "curioso", "apaixonado", "lindo", "beleza do idioma", "por hobby", "gosto muito da língua", "língua fascinante", "hobby", "por prazer", "curiosidade", "interesse pessoal", "amo o espanhol", "sempre tive sonho", "desejo aprender", "apaixonado por idiomas", "prazer em aprender", "gosto da cultura", "sonho aprender", "sempre gostei do idioma", "hobby", "curiosidade", "apaixonado", "estudo desde criança", "acho bonito", "me simpatizei", "me identifico", "acho interessante", "por diletantismo", "admiro", "amo a língua", "curto o idioma", "gosto", "acho legal", "sou apaixonado pelo idioma", "me gusta", "sou fã do idioma", "acho uma língua linda", "me interessei", "sonoridade bonita", "Tem muito amor por esse índioma,sou formada em gastronomia quero muito fala fluentemente ,porque futuramente vou abrir um restaurante tipo food truk viajando por todo os estados brasileiros ", "Eu aprecio muito o idioma e por ser falado em todo mudo e por ser usado e vários domínios, incluíndo a economia mundial e na política.", "É uma língua que eu acho que irei adaptar bem na pronúncia ", "Amor", "Aptidão ", "Por gostar ", "Sempre me senti interesseda no idioma já assisti novelas, séries em espanhol.", "A sonoridade das palavras me chamam muita a atenção. "
    ],
    "Aprendizado e Aperfeiçoamento": [
        "aprender", "conhecimento", "estudo", "aprimorar", "melhorar", "Para Atendimento online ", "Ampliar horizonte cultural", "saber", "capacitar", "educação", "aprendizado", "aprimoramento", "Eu faço live no tiktok e quero atingir novos publicos.", "para entender filmes", "diletantismo", "atendimento ao público latino", "pacientes da américa latina", "comunicação com cliente", "crescimento intelectual", "desenvolvimento pessoal", "repertório", "aprendizado", "estudo", "estudar espanhol", "expandir cultural e profissionalmente", "expandir meus horizontes", "aperfeiçoar", "melhoria pessoal", "para exercitar a mente", "me aperfeiçoar", "desenvolver mental", "para manter mente ativa", "por sabedoria", "para entender melhor", "acesso a conhecimento", "melhor compreensão cultural", "ler livros", "literatura", "intelectual", "explorar novos ares", "melhor desenvoltura", "melhor comunicação", "ter um segundo idioma", "segunda língua", "Sou estudante de Medicina no Paraguay, com grande dificuldade de comunicação no internato em Assuncion ", "Necessidade ", "Vontade", "Para lê mahwas", "Vontade ", "Por que eu tenho vontade de ser bilíngue e o espanhol língua atrativa ", "Agregar cultura e ter a tranquilidade pra falar e entender melhor ", "Reciclar", "Para entender quando assistir um filme ou uma série que seja em espanhol ", "Entender todos os sotaques e ampliar meu vocabulário.", "Pra ter uma visão mais global de mundo", "ampliar cultura geral", "Ampliar possibilidade de leitura", "Conseguir acessar conteúdos (livros, jornais, artigos, etc) superando as dificuldades linguísticas", "Falar sem medo", "para poder entender diálogos de séries e de nativos", "Fiz letras português/espanhol e preciso de vocabulário ", "Venho esrudando a cultura mexicana e aprendendo bastante. Me despertou a vontade.", "Não pensei em fluência. Por enquanto estou  experimentando coisas novas.", "Para me conunicar de foem natural", "Usar socialmente "
    ],
    "Intercâmbio": [
        "intercambio", "faculdade", "universidade", "curso", "estudar", "curso em buenos aires", "fazer faculdade", "curso fora", "estudar medicina", "estudar no paraguai", "faculdade fora", "doutorado", "universidade", "graduação",  "escola extracurricular", "intercâmbio", "plano de estudos fora", "enviar artigos internacionais", "ensino superior em outro país", "vestibular", "enem", "pré vestibular", "vida acadêmica", "fins acadêmicos", "para estudar fora", "mestrado", "pós doutorado", "pos", "pos graduacao", "incrementar currículo", "ajuda no currículo", "trunfo curricular"
    ],
    "Prova de Proficiência": [
        "dele", "certificado", "proficiencia", "teste", "prova", "prova de mestrado", "suficiência", "proficiencia", "prova de idioma", "certificado", "teste de proficiência", "suficiencia", "mestrado", "prova de idioma", "proficiencia", "prova de mestrado", "prova de idioma", "para prestar vestibular", "prova", "suficiência", "proficiencia"
    ],
    "Família": [
        "filho", "marido", "familia", "genro", "sobrinhos", "filho", "filha", "família mora", "marido", "esposo", "meu marido", "meu filho", "sobrinho", "neto", "genro", "visitar minha filha", "família hispana", "me enamore", "marido espanhol", "minha filha mora", "namorada cubana", "genro", "sou casada com espanhol", "meu namorado em lima", "para conversar com meus amigos", "meus amigos argentinos", "amigos fora do país", "amigos chilenos"
    ],
    "Voluntariado": [
        "missionaria", "igreja", "evangelismo", "religioso", "missao", "trabalho voluntário", "quero ajudar", "voluntariamente", "missão", "missionário", "igreja", "evangelizar", "ajudar venezuelanos", "missao",  "missionario", "evangelizar", "biblia", "pregar o evangelho", "missão", "evangelismo", "meu chamado", "igreja", "chamado"
    ],
    "Docência": [
        "professor", "ensinar", "lecionar", "docente", "dar aulas", "dar aula em espanhol", "ensinar", "sou professora", "vou cursar letras", "letras espanhol", "professor de espanhol", "docente", "ensinar espanhol", "ensinar", "dar aula", "professora", "docente", "lecionar"
    ],
    "Tradução e Interpretação": [
        "traducao", "interprete", "interpretacao", "tradutor", "musica", "tradução", "interpretar", "interpretação", "aula da minha profissão em espanhol", "tradução de textos acadêmicos"
    ],
    "Descendência Hispana": [
        "descendente", "sobrenome", "nacionalidade", "avo", "cidadania", "descendencia", "nome espanhol", "sou descendente", "esposo hispano", "familia hispana", "influência familiar", "conexão familiar", "tenho familiares", "familiares na espanha"
    ],
    "Já sou fluente / pré-fluente": [
        "fluente", "ja sei", "entendo", "falo um pouco", "pré-fluente", "já consigo assistir", "já sei um pouco", "já entendo", "entendo bem", "já sou fluente"
    ],
    "Sonho / Realização Pessoal": [
        "sonho", "objetivo", "realizacao", "prazer", "meta", "para chegar ao sucesso", "realizar sonho", "realização", "meta", "objetivo", "autonomia", "autorrealización", "para ser livre", "coragem", "superar bloqueios", "superar dificuldades", "me desafiar", "me testar", "realização pessoal",  "Acredito que eu tenho um propósito que ainda se revelará futuramente ", "Ser bilíngue ", "Ego"
    ],
    "Todas Alternativas Acima": [
        "todas", "alternativas", "um pouco de cada", "1, 2, 4 e 5", "todas alternativas", "um pouco de cada", "quero tudo isso", "quero tudo acima", "todos os motivos"
    ]
}