mapeamento_estados = {
    'SP': ['sao paulo', 'sao paulo sp', 'sp', 'sao paulo - sp', 'sao paulo capital', 'estado de sao paulo', 'barueri - sp', 'sao jose dos campos - sp', 'cidade de franca, interior de sao paulo', 'sao paulo - caieiras', 'sao paulo / sp', 'sao paulo.', 'sao paulo sp', 'sao paulo sp capital', 'jacupiranga', 'sao paulo sp.', 'sao paulo/sp', 'piracicaba-sp', 'guarulhos e bauru'],
    'RJ': ['rio de janeiro', 'rj', 'cabo frio - rio de janeiro', 'cabo frio - rj', 'rio da janeiro', 'rio de janeiro rj', 'rio de janeiro, rj', 'angra dos reis'],
    'MG': ['minas gerais', 'mg', 'minas  gerais', 'mias gerais', 'minas gerais / janauba', 'contagem', 'minas gerais/belo horizonte', 'minas  gerias', 'belo horizonte', 'uberlandia'],
    'RS': ['rio grande do sul', 'rs'],
    'PR': ['parana', 'pr', 'curitiba', 'curitiba parana', 'pr/curitiba', 'foz do iguacu/ pr'],
    'SC': ['santa catarina', 'sc', 'balneario camboriu sc'],
    'DF': ['distrito federal', 'df', 'brasilia', 'brasilia/df', 'brasilia df. capital', 'brasilia df', 'brasíla'],
    'GO': ['goias', 'goiania', 'goias / goiania', 'goias', 'góias'],
    'BA': ['bahia', 'salvador', 'salvador/bahia', 'bahia.'],
    'CE': ['ceara', 'ceará', 'fortaleza / ceará'],
    'PE': ['pernambuco', 'recife', 'recife pe'],
    'RN': ['rio grande do norte', 'rn', 'natal/ rio grande do norte'],
    'PB': ['paraiba'],
    'AM': ['amazonas', 'manaus', 'manaus/am', 'am'],
    'MT': ['mato grosso', 'mt'],
    'MS': ['mato grosso do sul', 'ms', 'campo grande'],
    'PA': ['para', 'pa', 'belem para', 'para (pa)', 'pará'],
    'AL': ['alagoas', 'maceio alagoas'],
    'PI': ['piaui', 'piauí', 'teresina'],
    'AP': ['amapá', 'amapa'],
    'RO': ['rondonia', 'ji-paraná - rondonia.', 'ro', 'rondônia', 'rondônia'],
    'ES': ['espirito santo', 'es', 'linhares-es'],
    'MA': ['maranhao'],
    'SE': ['sergipe'],
    'TO': ['tocantins'],
    'AC': ['acre'],
    'Estrangeiro': [
        'wisconsin', 'illinois', 'pennsylvania', 'girona', 'valencia', 'san miguel de tucuman',
        'porto', 'coruna', 'galicia', 'lleida', 'aveiro', 'bernall', 'assuncion', 'asturias',
        'tarragona', 'florida', 'toquio', 'almeria', 'poznan', 'lisboa',
        'quito', 'equador', 'braga', 'unhais da serra', 'cuneo/piemonte'
    ],
    'Não Informado': ['intermediario', '42424', 'caba', 'cdmx']
}